# Generated by Django 5.2.9 on 2025-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="school_photos/"),
        ),
    ]
